name: containers

permissions: write-all

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-bazel-ci
  BAZEL_VERSION: "6.1.1"

on:
  push:
    paths:
      - .devcontainer/bazel-zen/Dockerfile
    branches:
      - main
  workflow_dispatch:

jobs:
  push-bazel-container:
    runs-on: ubuntu-22.04
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Echo
      run: |
        echo "USER: ${{ github.actor }}"
        echo "REPOSITORY: ${{ github.repository }}"
        echo "TAGS: ${{ steps.meta.outputs.tags }}"
        echo "LABELS: ${{ steps.meta.outputs.labels }}"
    - name: Image - Bazel
      uses: docker/build-push-action@v3
      with:
        file: ./.devcontainer/bazel-zen/Dockerfile
        push: true
        build-args: |
            BAZEL_VERSION=${{ env.BAZEL_VERSION }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:bazel${{ env.BAZEL_VERSION }}
        labels: ${{ steps.meta.outputs.labels }}
